package myproject.currency_converter;

import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class ReturnCurrenciesList {

    public List<Currency> returnCurrencies() {
        List<Currency> currencies = new ArrayList<>();

        currencies.add(new Currency("AED", "united arab emirates dirham"));
        currencies.add(new Currency("AFN", "afghan afghani"));
        currencies.add(new Currency("ALL", "albanian lek"));
        currencies.add(new Currency("AMD", "armenian dram"));
        currencies.add(new Currency("ANG", "netherlands antillean guilder"));
        currencies.add(new Currency("AOA", "angolan kwanza"));
        currencies.add(new Currency("ARS", "argentine peso"));
        currencies.add(new Currency("AUD", "australian dollar"));
        currencies.add(new Currency("AWG", "aruban florin"));
        currencies.add(new Currency("AZN", "azerbaijani manat"));
        currencies.add(new Currency("BAM", "bosnia-herzegovina convertible mark"));
        currencies.add(new Currency("BBD", "barbadian dollar"));
        currencies.add(new Currency("BDT", "bangladeshi taka"));
        currencies.add(new Currency("BGN", "bulgarian lev"));
        currencies.add(new Currency("BHD", "bahraini dinar"));
        currencies.add(new Currency("BIF", "burundian franc"));
        currencies.add(new Currency("BMD", "bermudan dollar"));
        currencies.add(new Currency("BND", "brunei dollar"));
        currencies.add(new Currency("BOB", "bolivian boliviano"));
        currencies.add(new Currency("BRL", "brazilian real"));
        currencies.add(new Currency("BSD", "bahamian dollar"));
        currencies.add(new Currency("BTC", "bitcoin"));
        currencies.add(new Currency("BTN", "bhutanese ngultrum"));
        currencies.add(new Currency("BWP", "botswanan pula"));
        currencies.add(new Currency("BYN", "new belarusian ruble"));
        currencies.add(new Currency("BYR", "belarusian ruble"));
        currencies.add(new Currency("BZD", "belize dollar"));
        currencies.add(new Currency("CAD", "canadian dollar"));
        currencies.add(new Currency("CDF", "congolese franc"));
        currencies.add(new Currency("CHF", "swiss franc"));
        currencies.add(new Currency("CLF", "chilean unit of account (uf)"));
        currencies.add(new Currency("CLP", "chilean peso"));
        currencies.add(new Currency("CNY", "chinese yuan"));
        currencies.add(new Currency("COP", "colombian peso"));
        currencies.add(new Currency("CRC", "costa rican colón"));
        currencies.add(new Currency("CUC", "cuban convertible peso"));
        currencies.add(new Currency("CUP", "cuban peso"));
        currencies.add(new Currency("CVE", "cape verdean escudo"));
        currencies.add(new Currency("CZK", "czech republic koruna"));
        currencies.add(new Currency("DJF", "djiboutian franc"));
        currencies.add(new Currency("DKK", "danish krone"));
        currencies.add(new Currency("DOP", "dominican peso"));
        currencies.add(new Currency("DZD", "algerian dinar"));
        currencies.add(new Currency("EGP", "egyptian pound"));
        currencies.add(new Currency("ERN", "eritrean nakfa"));
        currencies.add(new Currency("ETB", "ethiopian birr"));
        currencies.add(new Currency("EUR", "euro"));
        currencies.add(new Currency("FJD", "fijian dollar"));
        currencies.add(new Currency("FKP", "falkland islands pound"));
        currencies.add(new Currency("GBP", "british pound sterling"));
        currencies.add(new Currency("GEL", "georgian lari"));
        currencies.add(new Currency("GGP", "guernsey pound"));
        currencies.add(new Currency("GHS", "ghanaian cedi"));
        currencies.add(new Currency("GIP", "gibraltar pound"));
        currencies.add(new Currency("GMD", "gambian dalasi"));
        currencies.add(new Currency("GNF", "guinean franc"));
        currencies.add(new Currency("GTQ", "guatemalan quetzal"));
        currencies.add(new Currency("GYD", "guyanaese dollar"));
        currencies.add(new Currency("HKD", "hong kong dollar"));
        currencies.add(new Currency("HNL", "honduran lempira"));
        currencies.add(new Currency("HRK", "croatian kuna"));
        currencies.add(new Currency("HTG", "haitian gourde"));
        currencies.add(new Currency("HUF", "hungarian forint"));
        currencies.add(new Currency("IDR", "indonesian rupiah"));
        currencies.add(new Currency("ILS", "israeli new sheqel"));
        currencies.add(new Currency("IMP", "manx pound"));
        currencies.add(new Currency("INR", "indian rupee"));
        currencies.add(new Currency("IQD", "iraqi dinar"));
        currencies.add(new Currency("IRR", "iranian rial"));
        currencies.add(new Currency("ISK", "icelandic króna"));
        currencies.add(new Currency("JEP", "jersey pound"));
        currencies.add(new Currency("JMD", "jamaican dollar"));
        currencies.add(new Currency("JOD", "jordanian dinar"));
        currencies.add(new Currency("JPY", "japanese yen"));
        currencies.add(new Currency("KES", "kenyan shilling"));
        currencies.add(new Currency("KGS", "kyrgystani som"));
        currencies.add(new Currency("KHR", "cambodian riel"));
        currencies.add(new Currency("KMF", "comorian franc"));
        currencies.add(new Currency("KPW", "north korean won"));
        currencies.add(new Currency("KRW", "south korean won"));
        currencies.add(new Currency("KWD", "kuwaiti dinar"));
        currencies.add(new Currency("KYD", "cayman islands dollar"));
        currencies.add(new Currency("KZT", "kazakhstani tenge"));
        currencies.add(new Currency("LAK", "laotian kip"));
        currencies.add(new Currency("LBP", "lebanese pound"));
        currencies.add(new Currency("LKR", "sri lankan rupee"));
        currencies.add(new Currency("LRD", "liberian dollar"));
        currencies.add(new Currency("LSL", "lesotho loti"));
        currencies.add(new Currency("LTL", "lithuanian litas"));
        currencies.add(new Currency("LVL", "latvian lats"));
        currencies.add(new Currency("LYD", "libyan dinar"));
        currencies.add(new Currency("MAD", "moroccan dirham"));
        currencies.add(new Currency("MDL", "moldovan leu"));
        currencies.add(new Currency("MGA", "malagasy ariary"));
        currencies.add(new Currency("MKD", "macedonian denar"));
        currencies.add(new Currency("MMK", "myanma kyat"));
        currencies.add(new Currency("MNT", "mongolian tugrik"));
        currencies.add(new Currency("MOP", "macanese pataca"));
        currencies.add(new Currency("MRO", "mauritanian ouguiya"));
        currencies.add(new Currency("MUR", "mauritian rupee"));
        currencies.add(new Currency("MVR", "maldivian rufiyaa"));
        currencies.add(new Currency("MWK", "malawian kwacha"));
        currencies.add(new Currency("MXN", "mexican peso"));
        currencies.add(new Currency("MYR", "malaysian ringgit"));
        currencies.add(new Currency("MZN", "mozambican metical"));
        currencies.add(new Currency("NAD", "namibian dollar"));
        currencies.add(new Currency("NGN", "nigerian naira"));
        currencies.add(new Currency("NIO", "nicaraguan córdoba"));
        currencies.add(new Currency("NOK", "norwegian krone"));
        currencies.add(new Currency("NPR", "nepalese rupee"));
        currencies.add(new Currency("NZD", "new zealand dollar"));
        currencies.add(new Currency("OMR", "omani rial"));
        currencies.add(new Currency("PAB", "panamanian balboa"));
        currencies.add(new Currency("PEN", "peruvian nuevo sol"));
        currencies.add(new Currency("PGK", "papua new guinean kina"));
        currencies.add(new Currency("PHP", "philippine peso"));
        currencies.add(new Currency("PKR", "pakistani rupee"));
        currencies.add(new Currency("PLN", "polish zloty"));
        currencies.add(new Currency("PYG", "paraguayan guarani"));
        currencies.add(new Currency("QAR", "qatari rial"));
        currencies.add(new Currency("RON", "romanian leu"));
        currencies.add(new Currency("RSD", "serbian dinar"));
        currencies.add(new Currency("RUB", "russian ruble"));
        currencies.add(new Currency("RWF", "rwandan franc"));
        currencies.add(new Currency("SAR", "saudi riyal"));
        currencies.add(new Currency("SBD", "solomon islands dollar"));
        currencies.add(new Currency("SCR", "seychellois rupee"));
        currencies.add(new Currency("SDG", "sudanese pound"));
        currencies.add(new Currency("SEK", "swedish krona"));
        currencies.add(new Currency("SGD", "singapore dollar"));
        currencies.add(new Currency("SHP", "saint helena pound"));
        currencies.add(new Currency("SLE", "sierra leonean leone"));
        currencies.add(new Currency("SLL", "sierra leonean leone"));
        currencies.add(new Currency("SOS", "somali shilling"));
        currencies.add(new Currency("SRD", "surinamese dollar"));
        currencies.add(new Currency("STD", "são tomé and príncipe dobra"));
        currencies.add(new Currency("SVC", "salvadoran colón"));
        currencies.add(new Currency("SYP", "syrian pound"));
        currencies.add(new Currency("SZL", "swazi lilangeni"));
        currencies.add(new Currency("THB", "thai baht"));
        currencies.add(new Currency("TJS", "tajikistani somoni"));
        currencies.add(new Currency("TMT", "turkmenistani manat"));
        currencies.add(new Currency("TND", "tunisian dinar"));
        currencies.add(new Currency("TOP", "tongan paʻanga"));
        currencies.add(new Currency("TRY", "turkish lira"));
        currencies.add(new Currency("TTD", "trinidad and tobago dollar"));
        currencies.add(new Currency("TWD", "new taiwan dollar"));
        currencies.add(new Currency("TZS", "tanzanian shilling"));
        currencies.add(new Currency("UAH", "ukrainian hryvnia"));
        currencies.add(new Currency("UGX", "ugandan shilling"));
        currencies.add(new Currency("USD", "united states dollar"));
        currencies.add(new Currency("UYU", "uruguayan peso"));
        currencies.add(new Currency("UZS", "uzbekistan som"));
        currencies.add(new Currency("VEF", "venezuelan bolívar fuerte"));
        currencies.add(new Currency("VES", "sovereign bolivar"));
        currencies.add(new Currency("VND", "vietnamese dong"));
        currencies.add(new Currency("VUV", "vanuatu vatu"));
        currencies.add(new Currency("WST", "samoan tala"));
        currencies.add(new Currency("XAF", "cfa franc beac"));
        currencies.add(new Currency("XAG", "silver (troy ounce)"));
        currencies.add(new Currency("XAU", "gold (troy ounce)"));
        currencies.add(new Currency("XCD", "east caribbean dollar"));
        currencies.add(new Currency("XDR", "special drawing rights"));
        currencies.add(new Currency("XOF", "cfa franc bceao"));
        currencies.add(new Currency("XPF", "cfp franc"));
        currencies.add(new Currency("YER", "yemeni rial"));
        currencies.add(new Currency("ZAR", "south african rand"));
        currencies.add(new Currency("ZMK", "zambian kwacha (pre-2013)"));
        currencies.add(new Currency("ZMW", "zambian kwacha"));
        currencies.add(new Currency("ZWL", "zimbabwean dollar"));

        return currencies;
    }
}
